name: Periodic ping

on:
  schedule:
    cron: '5 9 * * *'

jobs:
  ping:
    runs-on:  ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v2
        with:            
          url: "https://ci-pokedex.herokuapp.com/version"
